#Server configuration
server.port=8087
server.address=0.0.0.0

### DATABASE ###
spring.datasource.url=jdbc:mysql://mysqldb:3306/beetrackdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update




#logging configuration
logging.level.com.zaxxer.hikari=INFO
logging.level.org.springframework=INFO 
logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %-5level - %logger{60} - %msg%n
# Logging
logging.level.com.example=DEBUG

# JWT Configuration
jwt.secret=512b97a3458efbbf5c4a4029fa8ad0ca9fcca94c0027d1fcd131b23874df7ca9fe334dab919a47fc2ac7a83ba1ed6fb98b14d9ed15021fc2d148594714330d36
jwt.expiration=86400000





# Actuator and Prometheus Configuration
management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

