# Server Port
server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/beetrackdb
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Logging
logging.level.com.example=DEBUG

# JWT Configuration
jwt.secret=512b97a3458efbbf5c4a4029fa8ad0ca9fcca94c0027d1fcd131b23874df7ca9fe334dab919a47fc2ac7a83ba1ed6fb98b14d9ed15021fc2d148594714330d36
jwt.expiration=86400000